services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: node
    environment:
      - NODE_ENV=production
      - TZ=GMT
    ports:
      - 5173:5173 # dev page
    volumes:
      - ./frontend:/home/app

  # api:
  #   image: openjdk:latest
  #   container_name: AI-api
  #   working_dir: "/app"
  #   command: "java -jar Insurance-Demo-1.0-SNAPSHOT-jar-with-dependencies.jar"
  #   env_file:
  #     - api/.env
  #   restart: on-failure
  #   volumes:
  #     - ./api/target:/app
  #   ports:
  #     - 4567:4567
