name: Build

on:
  push:
    branches: [ "master", "multi-stage-dockers" ]

env:
  BUILD_TARGET: dev


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v3
      run: docker compose up frontend --build
    -
